TodoList/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
]

todo/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^(?P<order>|[a-z]+)$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/detail/', views.detail, name='detail'),
    url(r'^newtodo/$', views.newtodo, name='newtodo'),
    url(r'^(?P<pk>[0-9]+)/edittodo/', views.edittodo, name='edittodo'),
    url(r'^(?P<pk>[0-9]+)/delete/', views.delete, name='delete')
]

todo/models.py
from django.db import models
from django.utils import timezone


class TodoRevisions(models.Model):
    crev = models.IntegerField(default=0)

    def new_revision(self, status, des, due_date):
        to = self.todoitem_set.create(status=status, des=des, date_created=timezone.now(), due_date=due_date)
        self.crev = to.id
        self.save()

    def get_current_revision(self):
        return self.todoitem_set.get(id=self.crev)

    def get_current_revision_as_set(self):
        return self.todoitem_set.filter(id=self.crev)

    def __str__(self):
        return self.crev.__str__()


class TodoItem(models.Model):
    history = models.ForeignKey(TodoRevisions, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=200) #status of todo item
    des = models.CharField(max_length=500) #description of todo item
    date_created = models.DateTimeField('Date Created', null=True)
    due_date = models.DateTimeField('ToDo date', null=True)

    def __str__(self):
        return self.status



#from todo.models import TodoRevisions, TodoItem
#from django.utils import timezone
#.new_revision("test", "test", timezone.now())

todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from .models import TodoItem, TodoRevisions
from django.utils import timezone
from django.utils.dateparse import parse_datetime


def index(request, order):

    revs = TodoRevisions.objects.all().order_by('-crev')
    ret = TodoItem.objects.all().filter(id=-1)

    for r in revs:
        ret |= r.get_current_revision_as_set()

    order_map = {'obstat': 'status', 'obdes': 'des', 'obdc': 'date_created', 'obdd': 'due_date'}

    context = {'current_todos': ret}

    obstr = ''
    if order != '':
        if order[0] == 'r':
            obstr='-'
            order = order[1:]

        if order in order_map.keys():
            obstr += order_map[order]
            context = {'current_todos': ret.order_by(obstr)}

    return render(request, 'todo/index.html', context)


def detail(request, pk):
    tdi = get_object_or_404(TodoItem, pk=pk)

    dt_html_str = '{0}-{1:02d}-{2:02d}T{3:02d}:{4:02d}'.format(tdi.due_date.year, tdi.due_date.month, tdi.due_date.day, tdi.due_date.hour, tdi.due_date.minute)

    context = {'todoitem': tdi, 'past_revs': tdi.history.todoitem_set.all().order_by('-date_created'), 'html5date': dt_html_str}

    return render(request, 'todo/detail.html', context)


def newtodo(request):
    tdr = TodoRevisions()
    tdr.save()
    tdr.new_revision(request.POST['status'], request.POST['des'], parse_datetime(request.POST['due_date']))
    tdr.save()


    return HttpResponseRedirect(reverse('todo:index', kwargs={'order': ''}))

def edittodo(request, pk):
    tdi = get_object_or_404(TodoItem, pk=pk)
    tdr = tdi.history

    if request.POST['status'] != '' and request.POST['des'] != '' and request.POST['due_date'] != '':

        match = TodoItem.objects.all().exists

        if match != 0:

            tdr.new_revision(request.POST['status'], request.POST['des'], parse_datetime(request.POST['due_date']))
            tdr.save()

    return HttpResponseRedirect(reverse('todo:index', kwargs={'order': ''}))

def delete(request, pk):
    tdr = get_object_or_404(TodoRevisions, crev=pk)
    tdr.delete()

    return HttpResponseRedirect(reverse('todo:index', kwargs={'order': ''}))

todo/templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail View Todo -  {{ todoitem.status }}</title>
    <link rel = "stylesheet" type = "text/css" href="/static/todo/main.css" />
</head>
<body>
    <h1>Currennt Revision</h1>
    <form action="{% url 'todo:edittodo' todoitem.id %}" method = "POST">
        {% csrf_token %}
        <label>Status</label> <input type = "text" name = "status" value = {{ todoitem.status }} /> <br/>
        <label>Description</label> <input type = "text" name = "des" value = {{ todoitem.des }} /> <br/>
        <label>Due date</label> <input type = "datetime-local" name = "due_date" value = {{ html5date }} /> <br/>
        <label>Date Created: {{ todoitem.date_created }}</label> <br />
        <input type = "submit" value = "Submit Changes" />
    </form>

    <h1>Revision History</h1>
    <table>
    <tr>
        <th>Status</th>
        <th>Description</th>
        <th>Date/time Created</th>
        <th>Date Due</th>
    </tr>
    {% for to in past_revs %}
        <tr>
            <td>{{ to.status }}</td>
            <td>{{ to.des }}</td>
            <td>{{ to.date_created }}</td>
            <td>{{ to.due_date }}</td>
        </tr>
    {% endfor %}
    </table>

</body>
</html>

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo Items</title>

    <link rel = "stylesheet" type = "text/css" href="/static/todo/main.css" />

    <script>
        var d = new Date();
        var cdate = [d.getFullYear().toString(), d.getMonth().toString(), d.getDay().toString(), d.getHours().toString(), d.getMinutes().toString()]

        for(var i=1; i < cdate.length; i++)
        {
            if(cdate[i].length == 1)
            {
                cdate[i] = "0"+cdate[i];
            }
        }

        var value = cdate[0]+"-"+cdate[1]+"-"+cdate[2]+"T"+cdate[3]+":"+cdate[4];

    </script>

</head>
<body>
<h1>Todo Items</h1>

<form action="{% url 'todo:newtodo' %}" method="POST">
{% csrf_token %}
<table>
<tr>
    <th>Status (<a href="{% url 'todo:index' 'obstat' %}">A</a>, <a href="{% url 'todo:index' 'robstat' %}">D</a>)</th>
    <th>Description (<a href="{% url 'todo:index' 'obdes' %}">A</a>, <a href="{% url 'todo:index' 'robdes' %}">D</a>)</th>
    <th>Date/time Created (<a href="{% url 'todo:index' 'obdc' %}">A</a>, <a href="{% url 'todo:index' 'robdc' %}">D</a>)</th>
    <th>Date Due (<a href="{% url 'todo:index' 'obdd' %}">A</a>, <a href="{% url 'todo:index' 'robdd' %}">D</a>)</th>
    <th>Actions</th>
</tr>
{% for to in current_todos %}
    <tr>
        <td>{{ to.status }}</td>
        <td>{{ to.des }}</td>
        <td>{{ to.date_created }}</td>
        <td>{{ to.due_date }}</td>
        <td><a href = {% url 'todo:detail' to.id %}>View</a> <a href = {% url 'todo:delete' to.id %}>Delete</a></td>
    </tr>
{% endfor %}
    <tr style = "background-color: aqua;" class = editing>
        <td><input type = "text" name = "status" value = "New" /></td>
        <td><input type = "text" name = "des" /></td>
        <td>NOW</td>
        <td><input id = "new_stuff" type = "datetime-local" name = "due_date" /></td>
        <td><input type = "submit" value = "create"></td>
    </tr>
</table>
</form>

<script>
    document.getElementById("new_stuff").defaultValue = value;
</script>

</body>
</html>